id: I8BA916F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:21:07+00:00'
last_modified: '2022-06-07T14:01:51.205981+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9039
  title: ཡོངས་འཛིན་དཔལ་འབྱོར་རྒྱ་མཚོའི་དབུ་མ་སོགས་ཡིག་ཆ་སྣ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    76AE:
      image_group_id: I1KG9044
      title: ''
      total_pages: 788
      order: 1
      base_file: 76AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
