id: P001688
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9039
  title: ཡོངས་འཛིན་དཔལ་འབྱོར་རྒྱ་མཚོའི་དབུ་མ་སོགས་ཡིག་ཆ་སྣ་ཚོགས།
  author: ''
  volumes:
    6bde1bbe03e94d4eb6bc41a83e63034d:
      image_group_id: I1KG9044
      title: ''
      volume_number: 1
      total_pages: 788
