id: P001688
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:14:47.418794
source_metadata:
  id: bdr:W1KG9039
  title: ཡོངས་འཛིན་དཔལ་འབྱོར་རྒྱ་མཚོའི་དབུ་མ་སོགས་ཡིག་ཆ་སྣ་ཚོགས།
  author: ''
  volumes:
    6bde1bbe03e94d4eb6bc41a83e63034d:
      image_group_id: I1KG9044
      title: ''
      volume_number: 1
      total_pages: 788
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
